In [1]:
# examples and exercises in chapter 2.4 of the Chinese version of book "Joyful Pandas" (pandas数据处理与分析)

In [2]:
import numpy as np
import pandas as pd

In [3]:
import os
os.chdir("../../")

In [4]:
s = pd.Series([1,2,3,4,5])
roller = s.rolling(window=3)
roller

Rolling [window=3,center=False,axis=0,method=single]

In [5]:
roller.mean()

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64

In [6]:
roller.sum()

0     NaN
1     NaN
2     6.0
3     9.0
4    12.0
dtype: float64

In [7]:
roller.max()

0    NaN
1    NaN
2    3.0
3    4.0
4    5.0
dtype: float64

In [8]:
s2 = pd.Series([1,2,6,16,30])
roller.cov(s2)

0     NaN
1     NaN
2     2.5
3     7.0
4    12.0
dtype: float64

In [9]:
roller.corr(s2)

0         NaN
1         NaN
2    0.944911
3    0.970725
4    0.995402
dtype: float64

In [27]:
np.corrcoef([1,2,3], [1,2,6]), np.cov([2,3,4], [2,6,16])

(array([[1.        , 0.94491118],
        [0.94491118, 1.        ]]),
 array([[ 1.,  7.],
        [ 7., 52.]]))

In [26]:
np.corrcoef(s, s2)

array([[1.        , 0.93577544],
       [0.93577544, 1.        ]])

In [28]:
roller.apply(lambda x:x.mean())

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64

In [29]:
s = pd.Series([1,3,6,10,15])
s.shift(2)

0    NaN
1    NaN
2    1.0
3    3.0
4    6.0
dtype: float64

In [30]:
s.diff(3)

0     NaN
1     NaN
2     NaN
3     9.0
4    12.0
dtype: float64

In [31]:
s.pct_change()

0         NaN
1    2.000000
2    1.000000
3    0.666667
4    0.500000
dtype: float64

In [32]:
s.shift(-1)

0     3.0
1     6.0
2    10.0
3    15.0
4     NaN
dtype: float64

In [33]:
s.diff(-2)

0   -5.0
1   -7.0
2   -9.0
3    NaN
4    NaN
dtype: float64

In [34]:
# Ex2-7

In [37]:
np.diff(np.array([1,2,3]))

array([1, 1])

In [39]:
s.rolling(3).apply(lambda x:list(x)[0]) #s.shift(2)

0    NaN
1    NaN
2    1.0
3    3.0
4    6.0
dtype: float64

In [41]:
s.rolling(4).apply(lambda x:list(x)[-1] - list(x)[0]) # s.diff(3)

0     NaN
1     NaN
2     NaN
3     9.0
4    12.0
dtype: float64

In [42]:
def my_pct(x):
    L = list(x)
    return L[-1] / L[0] - 1
s.rolling(2).apply(my_pct) # s.pct_change()

0         NaN
1    2.000000
2    1.000000
3    0.666667
4    0.500000
dtype: float64

In [43]:
# Ex2-8

In [55]:
s = pd.Series([1,2,3,4])
window = 2
s.rolling(window).sum().shift(-(window-1))

0    3.0
1    5.0
2    7.0
3    NaN
dtype: float64

In [56]:
# 2.4.2

In [58]:
s = pd.Series([1,3,6,10])
s.expanding().mean()

0    1.000000
1    2.000000
2    3.333333
3    5.000000
dtype: float64

In [59]:
s.values.cumsum()

array([ 1,  4, 10, 20])

In [60]:
s.values.cumprod()

array([  1,   3,  18, 180])

In [61]:
s.cumsum()

0     1
1     4
2    10
3    20
dtype: int64

In [62]:
s.cumprod()

0      1
1      3
2     18
3    180
dtype: int64

In [63]:
s.expanding().apply(lambda x:x.sum())

0     1.0
1     4.0
2    10.0
3    20.0
dtype: float64

In [64]:
s.expanding().apply(lambda x:x.prod())

0      1.0
1      3.0
2     18.0
3    180.0
dtype: float64