In [ ]:
# examples in chapter 1.2 of the Chinese version of book "Joyful Pandas" (pandas数据处理与分析)

In [1]:
# 1.2.1

In [2]:
import numpy as np

In [10]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [12]:
a = np.array([[1, 2, 3]])
a.shape

(1, 3)

In [4]:
a = np.linspace(1, 100)
a.shape

(50,)

In [6]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [7]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
np.ones((2, 1, 2))

array([[[1., 1.]],

       [[1., 1.]]])

In [13]:
np.full((2, 3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [15]:
np_input = np.array([[1, 2], [3, 4], [5, 6]])
np_input.shape

(3, 2)

In [19]:
np.full((3, 2, 3, 2), np_input)

array([[[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]])

In [24]:
arr = [[1, 2], [3, 4]]
np.full_like(arr, [200, 100])

array([[200, 100],
       [200, 100]])

In [27]:
np.eye(3, k=-1) + np.eye(3, k=1) + np.eye(3)

array([[1., 1., 0.],
       [1., 1., 1.],
       [0., 1., 1.]])

In [34]:
np.empty((2, 3), "float64")

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.random.uniform(-1, 3, (3, 3))

array([[ 1.48734681, -0.71289163,  2.87212081],
       [ 2.82043069,  1.56830722, -0.28489463],
       [-0.15626327,  0.15474501, -0.80958916]])

In [39]:
np.random.rand(3, 3)

array([[0.64177161, 0.31950757, 0.06209023],
       [0.26833218, 0.37117044, 0.21285741],
       [0.78797975, 0.49147346, 0.94735478]])

In [40]:
np.random.normal(3, 2.5, (3, 3))

array([[ 4.95898468,  5.62480954,  1.1681151 ],
       [ 5.74958397,  4.09589212,  9.10004254],
       [ 4.65314111,  5.07097356, -1.51218571]])

In [41]:
np.random.randn(3, 3)

array([[-1.70666076, -1.79264232,  0.83077232],
       [-0.13998896,  0.14521748,  0.99999846],
       [ 2.48849604,  0.93708101, -1.27135352]])

In [42]:
np.random.randint(5, 15, (3, 3))

array([[ 8,  7, 12],
       [12,  6,  8],
       [ 7,  8, 10]])

In [44]:
my_list = list("abcd")
np.random.choice(my_list, 3, replace=False, p=[0.1, 0.7, 0.1, 0.1])

array(['b', 'a', 'd'], dtype='<U1')

In [48]:
np.random.choice(my_list, (3, 3), replace=True)

array([['b', 'd', 'b'],
       ['c', 'a', 'a'],
       ['c', 'b', 'd']], dtype='<U1')

In [51]:
np.random.seed(0)
np.random.permutation(my_list)

array(['c', 'd', 'b', 'a'], dtype='<U1')

In [53]:
np.random.seed(0)
np.random.choice(my_list, 4, replace=False)

array(['c', 'd', 'b', 'a'], dtype='<U1')

In [54]:
# 1.2.2

In [55]:
carbon = np.random.rand(360, 180, 3)
res = carbon.transpose(2, 0, 1)
res.shape

(3, 360, 180)

In [56]:
res = carbon.T
res.shape

(3, 180, 360)

In [59]:
my_matrix = np.arange(8)
my_matrix.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
my_matrix.reshape((2, 4), order="C")

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
my_matrix.reshape((2, 4), order="F")

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [67]:
my_matrix.reshape((2, 4), order="C").reshape(8, order="F")

array([0, 4, 1, 5, 2, 6, 3, 7])

In [68]:
my_matrix.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
my_matrix.reshape(2, -1, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
my_matrix.reshape(-1, 2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
target = np.ones((2, 2))
expanded_target = np.expand_dims(target, (0, 2))
expanded_target.shape

(1, 2, 1, 2)

In [74]:
np.squeeze(expanded_target, (0, 2))

array([[1., 1.],
       [1., 1.]])

In [76]:
pop_man = np.random.rand(20, 6, 3)
pop_women = np.random.rand(20, 6, 3)
res = np.stack([pop_man, pop_women], axis=2)
res.shape

(20, 6, 2, 3)

In [77]:
pop_1_6 = np.random.rand(20, 6, 3)
pop_7_12 = np.random.rand(20, 6, 3)
res = np.concatenate([pop_1_6, pop_7_12], axis=1)
res.shape

(20, 12, 3)

In [79]:
res = np.split(pop_1_6, indices_or_sections=3, axis=1)
for i in res:
    print(i.shape)

(20, 2, 3)
(20, 2, 3)
(20, 2, 3)


In [80]:
res = np.split(pop_1_6, indices_or_sections=[1, 4], axis=1)
for i in res:
    print(i.shape)

(20, 1, 3)
(20, 3, 3)
(20, 2, 3)


In [82]:
# Ex1-5
# split() is more like the inverse of concatenate() because it doesn't introduce a new dimension

In [88]:
a = np.arange(3)
np.repeat(a, repeats=2)

array([0, 0, 1, 1, 2, 2])

In [85]:
np.repeat(a, repeats=a+1)

array([0, 1, 1, 2, 2, 2])

In [93]:
a = np.array([[1, 2], [3, 4]])
print(a.shape)

In [93]:
np.repeat(a, repeats=[1, 2], axis=1)

(2, 2)


array([[1, 2, 2],
       [3, 4, 4]])

In [94]:
np.repeat(a, repeats=[1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [95]:
# Ex1-6

In [100]:
a = np.arange(1, 11, 1).reshape((1, 10))
np.repeat(a, repeats=10, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [103]:
a = np.arange(1, 11, 1).reshape((10, 1))
np.repeat(a, repeats=10, axis=1)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [104]:
# 1.2.3

In [105]:
target = np.arange(24).reshape(4, 2, 3)
target

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [106]:
target[0:3, :, 1:3]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

In [108]:
target[[0, 1], [0, 1], [0, 1]]

array([ 0, 10])

In [109]:
target[0:2, 0:2, 0:2]

array([[[ 0,  1],
        [ 3,  4]],

       [[ 6,  7],
        [ 9, 10]]])

In [111]:
target[[True, False, True, False]]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [112]:
target[:, :, 0::2].shape == target[..., 0::2].shape

True

In [113]:
target[:, :, 0::2]

array([[[ 0,  2],
        [ 3,  5]],

       [[ 6,  8],
        [ 9, 11]],

       [[12, 14],
        [15, 17]],

       [[18, 20],
        [21, 23]]])

In [114]:
# Ex1-7

In [117]:
arr = np.arange(10)
arr[-2:-10:-3]

array([8, 5, 2])

In [128]:
target[:, np.newaxis, np.newaxis].shape

(4, 1, 1, 2, 3)

In [121]:
target[:, np.newaxis, :, np.newaxis].shape

(4, 1, 2, 1, 3)

In [127]:
target[..., np.newaxis, :, np.newaxis].shape

(4, 2, 1, 3, 1)

In [129]:
# 1.2.4

In [4]:
piece = np.random.randint(0, 5, (5, 3))
price = np.random.uniform(10, 100, 3)

In [5]:
piece * price

array([[ 78.83555315, 192.95332555,  56.15264479],
       [315.34221261, 192.95332555, 112.30528958],
       [  0.        , 257.27110074, 224.61057916],
       [ 78.83555315, 128.63555037,   0.        ],
       [236.50665946, 257.27110074, 168.45793437]])

In [6]:
# Ex1-8

In [11]:
a = np.random.rand(1, 3, 5)
b = np.random.rand(3, 1)
(a*b).shape

(1, 3, 5)

In [12]:
a = np.random.rand(3, 5, 3, 4)
b = np.random.rand(1, 3, 1)
(a*b).shape

(3, 5, 3, 4)

In [13]:
a = np.random.rand(3, 2, 1, 5)
b = np.random.rand(2, 5)
(a*b).shape

(3, 2, 2, 5)

In [17]:
piece.T * price.reshape(3, 1)

array([[ 78.83555315, 315.34221261,   0.        ,  78.83555315,
        236.50665946],
       [192.95332555, 192.95332555, 257.27110074, 128.63555037,
        257.27110074],
       [ 56.15264479, 112.30528958, 224.61057916,   0.        ,
        168.45793437]])

In [18]:
piece.T * price[:, np.newaxis]

array([[ 78.83555315, 315.34221261,   0.        ,  78.83555315,
        236.50665946],
       [192.95332555, 192.95332555, 257.27110074, 128.63555037,
        257.27110074],
       [ 56.15264479, 112.30528958, 224.61057916,   0.        ,
        168.45793437]])

In [19]:
# Ex1-9

In [20]:
piece.T * np.expand_dims(price, 1)

array([[ 78.83555315, 315.34221261,   0.        ,  78.83555315,
        236.50665946],
       [192.95332555, 192.95332555, 257.27110074, 128.63555037,
        257.27110074],
       [ 56.15264479, 112.30528958, 224.61057916,   0.        ,
        168.45793437]])

In [21]:
# 1.2.5

In [22]:
my_matrix = np.random.randint(20, 40, 24).reshape(2, 3, 4)

In [23]:
my_matrix.sum()

686

In [24]:
my_matrix.sum(axis=(1, 2))

array([388, 298])

In [25]:
my_matrix.sum(axis=0)

array([[60, 60, 47, 55],
       [55, 59, 59, 45],
       [65, 69, 56, 56]])

In [26]:
# Ex1-10

In [27]:
my_matrix.sum(axis=(0, 2))

array([222, 218, 246])

In [28]:
my_matrix.max(axis=(1, 2))

array([39, 36])

In [29]:
np.quantile(my_matrix, axis=-1, q=0.5)

array([[31. , 33.5, 35. ],
       [20.5, 21. , 30. ]])

In [30]:
np.median(my_matrix, axis=-1)

array([[31. , 33.5, 35. ],
       [20.5, 21. , 30. ]])

In [32]:
my_matrix = my_matrix.astype("float")
my_matrix[0, 0, 0] = np.nan
my_matrix.max(axis=(1, 2))

array([nan, 36.])

In [33]:
np.nanmax(my_matrix, axis=(1, 2))

array([39., 36.])

In [34]:
target1 = np.array([1, 3, 5, 9])
target2 = np.array([1, 5, 3, -9])
np.cov(target1, target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [43]:
corr = np.corrcoef(target1, target2)
corr

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

In [55]:
v = np.diag([np.std(target1), np.std(target2)])
v

array([[2.95803989, 0.        ],
       [0.        , 5.38516481]])

In [56]:
v @ corr @ v

array([[  8.75, -12.5 ],
       [-12.5 ,  29.  ]])

In [57]:
target = np.arange(-4, 5).reshape(3, -1)
np.abs(target)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [58]:
np.power(target, 2)

array([[16,  9,  4],
       [ 1,  0,  1],
       [ 4,  9, 16]])

In [59]:
two, ten = 2 * np.ones(2), 10 * np.ones(2)
np.abs(np.log(ten) / np.log(two) - np.log2(ten)) < 1e-15

array([ True,  True])

In [60]:
# Ex 1-11

In [71]:
target = np.random.randn(4, 3)
np.exp(target) / np.sum(target, axis=1).reshape(4, -1)

array([[ 1.72696684e+00,  1.90092679e+01,  1.46702384e+00],
       [-2.26442565e-01, -5.33841276e-01, -1.70457382e-02],
       [-1.33096759e-01, -1.64336530e+00, -3.69129939e-02],
       [ 7.89429880e-01,  4.09767251e+00,  1.87880545e+00]])

In [70]:
np.sum(target, axis=1).reshape(4, -1)

array([[ 1.89161028],
       [ 0.09730544],
       [ 2.03092035],
       [-4.14756047]])

In [73]:
salary = np.array([[9000, 11000], [11000, 12000]])
(salary > 10000).all(axis=1)

array([False,  True])

In [74]:
(salary > 10000).any(axis=1)

array([ True,  True])

In [75]:
# Ex 1-12

In [81]:
a = np.random.randint(0, 10, (2, 3, 4))
b = np.random.randint(0, 10, (3, 1))
a | b

array([[[ 5,  1,  1,  8],
        [ 0,  7,  2,  2],
        [ 5,  6, 13, 12]],

       [[ 2,  0,  1,  4],
        [ 0,  3,  0,  7],
        [ 7, 12,  6, 13]]])

In [84]:
target = np.random.randint(0, 10, (4, 5))
print(target)
row_max = (target >= target.max(axis=1)[:, np.newaxis]).astype("int")
row_max

[[6 9 0 9 3]
 [3 4 2 3 0]
 [2 7 7 7 9]
 [3 3 8 9 2]]


array([[0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0]])

In [85]:
my_array = np.random.rand(1000, 3)
condition1 = ~(my_array.sum(1)>1.5)
condition2 = (my_array[:, 0]>0.5) & (my_array[:, 2]>0.5)
res = my_array[condition1 | condition2, :]

In [86]:
((res.sum(1)<=1.5) | (res[:, [0, 2]]>0.5).all(1)).all()

True

In [96]:
# Ex1-13

In [105]:
target = np.round(np.random.rand(10, 3))
condition = target.sum(axis=1)<=1
res = target[condition]
print(res)
(res.sum(axis=1)<=1).all()

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


True

In [120]:
target = np.round(np.random.rand(10, 3))
condition = target.sum(axis=1)<3
res = target[condition]
print(res)
(res.sum(axis=1)<3).all()

[[0. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


True

In [121]:
target = np.round(np.random.rand(10, 3))
condition1 = target.sum(axis=1)<3
condition2 = target.sum(axis=1)>0
res = target[condition1 & condition2]
print(res)
((res.sum(axis=1)<3) & (res.sum(axis=1)>0)).all()

[[0. 1. 1.]
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 1. 0.]
 [0. 1. 1.]]


True

In [122]:
a = np.arange(4).reshape(-1, 2)
np.where(a>1, a.sum(0), a.sum(1))

array([[1, 5],
       [2, 4]])

In [124]:
# Ex1-14

In [127]:
def clip(array, min, max):
    tmp = np.where(array>=max, max, array)
    return np.where(tmp<=min, min, tmp)

target = np.random.randn(4, 3)
(np.clip(target, -1, 1) == clip(target, -1, 1)).all()

True

In [128]:
a = np.array([0, -5, 0, 1, 3, -1])
np.nonzero(a)

(array([1, 3, 4, 5]),)

In [129]:
a.argmax()

4

In [130]:
a.argmin()

1

In [131]:
# Ex1-15

In [137]:
target = np.random.randint(-3, 3, (4, 3))
target

array([[-1,  2, -1],
       [ 0,  0,  2],
       [-2, -1, -2],
       [-2, -3, -1]])

In [145]:
# The answer is yes because two indices array are return
np.nonzero(target)

(array([0, 0, 0, 1, 2, 2, 2, 3, 3, 3]), array([0, 1, 2, 2, 0, 1, 2, 0, 1, 2]))

In [144]:
target[np.nonzero(target)]

array([-1,  2, -1,  2, -2, -1, -2, -2, -3, -1])