In [ ]:
# examples in chapter 1.2 of the Chinese version of book "Joyful Pandas" (pandas数据处理与分析)

In [1]:
# 1.2.1

In [2]:
import numpy as np

In [10]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [12]:
a = np.array([[1, 2, 3]])
a.shape

(1, 3)

In [4]:
a = np.linspace(1, 100)
a.shape

(50,)

In [6]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [7]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
np.ones((2, 1, 2))

array([[[1., 1.]],

       [[1., 1.]]])

In [13]:
np.full((2, 3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [15]:
np_input = np.array([[1, 2], [3, 4], [5, 6]])
np_input.shape

(3, 2)

In [19]:
np.full((3, 2, 3, 2), np_input)

array([[[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]])

In [24]:
arr = [[1, 2], [3, 4]]
np.full_like(arr, [200, 100])

array([[200, 100],
       [200, 100]])

In [27]:
np.eye(3, k=-1) + np.eye(3, k=1) + np.eye(3)

array([[1., 1., 0.],
       [1., 1., 1.],
       [0., 1., 1.]])

In [34]:
np.empty((2, 3), "float64")

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.random.uniform(-1, 3, (3, 3))

array([[ 1.48734681, -0.71289163,  2.87212081],
       [ 2.82043069,  1.56830722, -0.28489463],
       [-0.15626327,  0.15474501, -0.80958916]])

In [39]:
np.random.rand(3, 3)

array([[0.64177161, 0.31950757, 0.06209023],
       [0.26833218, 0.37117044, 0.21285741],
       [0.78797975, 0.49147346, 0.94735478]])

In [40]:
np.random.normal(3, 2.5, (3, 3))

array([[ 4.95898468,  5.62480954,  1.1681151 ],
       [ 5.74958397,  4.09589212,  9.10004254],
       [ 4.65314111,  5.07097356, -1.51218571]])

In [41]:
np.random.randn(3, 3)

array([[-1.70666076, -1.79264232,  0.83077232],
       [-0.13998896,  0.14521748,  0.99999846],
       [ 2.48849604,  0.93708101, -1.27135352]])

In [42]:
np.random.randint(5, 15, (3, 3))

array([[ 8,  7, 12],
       [12,  6,  8],
       [ 7,  8, 10]])

In [44]:
my_list = list("abcd")
np.random.choice(my_list, 3, replace=False, p=[0.1, 0.7, 0.1, 0.1])

array(['b', 'a', 'd'], dtype='<U1')

In [48]:
np.random.choice(my_list, (3, 3), replace=True)

array([['b', 'd', 'b'],
       ['c', 'a', 'a'],
       ['c', 'b', 'd']], dtype='<U1')

In [51]:
np.random.seed(0)
np.random.permutation(my_list)

array(['c', 'd', 'b', 'a'], dtype='<U1')

In [53]:
np.random.seed(0)
np.random.choice(my_list, 4, replace=False)

array(['c', 'd', 'b', 'a'], dtype='<U1')

In [54]:
# 1.2.2

In [55]:
carbon = np.random.rand(360, 180, 3)
res = carbon.transpose(2, 0, 1)
res.shape

(3, 360, 180)

In [56]:
res = carbon.T
res.shape

(3, 180, 360)

In [59]:
my_matrix = np.arange(8)
my_matrix.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
my_matrix.reshape((2, 4), order="C")

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
my_matrix.reshape((2, 4), order="F")

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [67]:
my_matrix.reshape((2, 4), order="C").reshape(8, order="F")

array([0, 4, 1, 5, 2, 6, 3, 7])

In [68]:
my_matrix.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
my_matrix.reshape(2, -1, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
my_matrix.reshape(-1, 2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
target = np.ones((2, 2))
expanded_target = np.expand_dims(target, (0, 2))
expanded_target.shape

(1, 2, 1, 2)

In [74]:
np.squeeze(expanded_target, (0, 2))

array([[1., 1.],
       [1., 1.]])

In [76]:
pop_man = np.random.rand(20, 6, 3)
pop_women = np.random.rand(20, 6, 3)
res = np.stack([pop_man, pop_women], axis=2)
res.shape

(20, 6, 2, 3)

In [77]:
pop_1_6 = np.random.rand(20, 6, 3)
pop_7_12 = np.random.rand(20, 6, 3)
res = np.concatenate([pop_1_6, pop_7_12], axis=1)
res.shape

(20, 12, 3)

In [79]:
res = np.split(pop_1_6, indices_or_sections=3, axis=1)
for i in res:
    print(i.shape)

(20, 2, 3)
(20, 2, 3)
(20, 2, 3)


In [80]:
res = np.split(pop_1_6, indices_or_sections=[1, 4], axis=1)
for i in res:
    print(i.shape)

(20, 1, 3)
(20, 3, 3)
(20, 2, 3)


In [82]:
# Ex1-5
# split() is more like the inverse of concatenate() because it doesn't introduce a new dimension

In [88]:
a = np.arange(3)
np.repeat(a, repeats=2)

array([0, 0, 1, 1, 2, 2])

In [85]:
np.repeat(a, repeats=a+1)

array([0, 1, 1, 2, 2, 2])

In [93]:
a = np.array([[1, 2], [3, 4]])
print(a.shape)

In [93]:
np.repeat(a, repeats=[1, 2], axis=1)

(2, 2)


array([[1, 2, 2],
       [3, 4, 4]])

In [94]:
np.repeat(a, repeats=[1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [95]:
# Ex1-6

In [100]:
a = np.arange(1, 11, 1).reshape((1, 10))
np.repeat(a, repeats=10, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [103]:
a = np.arange(1, 11, 1).reshape((10, 1))
np.repeat(a, repeats=10, axis=1)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [104]:
# 1.2.3

In [105]:
target = np.arange(24).reshape(4, 2, 3)
target

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [106]:
target[0:3, :, 1:3]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

In [108]:
target[[0, 1], [0, 1], [0, 1]]

array([ 0, 10])

In [109]:
target[0:2, 0:2, 0:2]

array([[[ 0,  1],
        [ 3,  4]],

       [[ 6,  7],
        [ 9, 10]]])

In [111]:
target[[True, False, True, False]]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [112]:
target[:, :, 0::2].shape == target[..., 0::2].shape

True

In [113]:
target[:, :, 0::2]

array([[[ 0,  2],
        [ 3,  5]],

       [[ 6,  8],
        [ 9, 11]],

       [[12, 14],
        [15, 17]],

       [[18, 20],
        [21, 23]]])

In [114]:
# Ex1-7

In [117]:
arr = np.arange(10)
arr[-2:-10:-3]

array([8, 5, 2])

In [128]:
target[:, np.newaxis, np.newaxis].shape

(4, 1, 1, 2, 3)

In [121]:
target[:, np.newaxis, :, np.newaxis].shape

(4, 1, 2, 1, 3)

In [127]:
target[..., np.newaxis, :, np.newaxis].shape

(4, 2, 1, 3, 1)

In [129]:
# 1.2.4