In [1]:
# exercises in chapter 1.3 of the Chinese version of book "Joyful Pandas" (pandas数据处理与分析)

In [4]:
import numpy as np

In [5]:
# 1

In [6]:
A = np.arange(6).reshape(2, -1)
B = np.arange(6).reshape(3, -1)

In [7]:
A @ B

array([[10, 13],
       [28, 40]])

In [27]:
np.array([[(x*y).sum() for y in B.T[:, :]] for x in A[:, :]]) == A @ B

array([[ True,  True],
       [ True,  True]])

In [28]:
# 2

In [29]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))

In [30]:
A

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11]])

In [43]:
B = A.sum(1)[:, np.newaxis] @ (A.sum(0)[np.newaxis, :]) / A.sum()
B

array([[14.14211438, 13.08145581, 15.20277296, 13.67071057, 11.90294627],
       [15.18197574, 14.04332756, 16.32062392, 14.67590988, 12.77816291],
       [16.63778163, 15.38994801, 17.88561525, 16.08318891, 14.0034662 ],
       [16.42980936, 15.19757366, 17.66204506, 15.88214905, 13.82842288],
       [17.67764298, 16.35181976, 19.0034662 , 17.08838821, 14.87868284],
       [12.68630849, 11.73483536, 13.63778163, 12.26343154, 10.67764298],
       [13.93414211, 12.88908146, 14.97920277, 13.46967071, 11.72790295],
       [13.3102253 , 12.31195841, 14.3084922 , 12.86655113, 11.20277296]])

In [45]:
C = np.power(A-B, 2) / B
C.sum()

11.842696601945802

In [49]:
import scipy
scipy.stats.chisquare(A.reshape(40), B.reshape(40))

Power_divergenceResult(statistic=11.842696601945802, pvalue=0.9999920078268285)